### ISSUE TITLE
LED-Arduino nnot compiling

### ISSUE THREAD

**Issue by lstremfelj** [DIY-Machines/Kinetic-Sand-Art-Table#5]
When trying to compile in arduino ide 2.0 error mesage apears :

"Compilation error: WS2812FX.h: No such file or directory"  

This is when opening the .ino file in the LED-Arduino folder downloaded from Github

Few minutes later: 

Apologies - writing here to quickly. Did not read the comment in the ino file. It contains a loink where the missing library can be found and then installed.

**Comment by DIY-Machines** [comment]
Excellent and no problem. 😊  I just came here to tell you about the library as well.
Thanks for letting me know that you resolved it. Enjoy the project.
